name: delete derived data workflow
on:
  workflow_dispatch:

jobs:
  clean-configure:
    runs-on: macos-latest

    steps:
    
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Delete Derived Data
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
          
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Select xcode
        run: sudo xcode-select switch /Applications/Xcode_15.0.app
        
      - name: Xcode Version
        run: /usr/bin/xcodebuild -version
        
        
